"""features/organizing。详见 contract.py。"""

from features.organizing.contract import (
    JOB_KIND_ADD_FOLDER,
    JOB_KIND_ADD_TAG,
    JOB_KIND_ITEM,
    JOB_KIND_PURGE,
    JOB_KIND_REMOVE_FOLDER,
    JOB_KIND_REMOVE_TAG,
    JOB_KIND_RESTORE,
    JOB_KIND_SOFT_DELETE,
    BatchOutcome,
    BatchResult,
    WorkNotInTrash,
    bulk_add_tag,
    bulk_add_to_folder,
    bulk_remove_from_folder,
    bulk_remove_tag,
    bulk_restore,
    bulk_soft_delete,
    create_tag_and_apply,
    purge_works,
)

__all__ = [
    "JOB_KIND_ADD_FOLDER",
    "JOB_KIND_ADD_TAG",
    "JOB_KIND_ITEM",
    "JOB_KIND_PURGE",
    "JOB_KIND_REMOVE_FOLDER",
    "JOB_KIND_REMOVE_TAG",
    "JOB_KIND_RESTORE",
    "JOB_KIND_SOFT_DELETE",
    "BatchOutcome",
    "BatchResult",
    "WorkNotInTrash",
    "bulk_add_tag",
    "bulk_add_to_folder",
    "bulk_remove_from_folder",
    "bulk_remove_tag",
    "bulk_restore",
    "bulk_soft_delete",
    "create_tag_and_apply",
    "purge_works",
]
