"""caps/httpfetch。详见 contract.py。"""

from caps.httpfetch.contract import (
    ALLOWED_SCHEMES,
    DEFAULT_BACKOFF_BASE,
    DEFAULT_BACKOFF_MAX,
    DEFAULT_MAX_REDIRECTS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_STATUSES,
    DEFAULT_TIMEOUT,
    DEFAULT_USER_AGENT,
    FetchResult,
    HttpFetchError,
    HttpStatusError,
    NetworkError,
    RateLimiter,
    TooManyRedirects,
    UnsafeURL,
    check_url_safety,
    default_resolve,
    fetch,
    is_safe_ip,
)

__all__ = [
    "ALLOWED_SCHEMES",
    "DEFAULT_BACKOFF_BASE",
    "DEFAULT_BACKOFF_MAX",
    "DEFAULT_MAX_REDIRECTS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_STATUSES",
    "DEFAULT_TIMEOUT",
    "DEFAULT_USER_AGENT",
    "FetchResult",
    "HttpFetchError",
    "HttpStatusError",
    "NetworkError",
    "RateLimiter",
    "TooManyRedirects",
    "UnsafeURL",
    "check_url_safety",
    "default_resolve",
    "fetch",
    "is_safe_ip",
]
